export type Movie = {
  id: number;
  title: string;
  originalTitle?: string;
  description?: string;
  plot?: string;
  posterUrl?: string;
  backdropUrl?: string;
  releaseYear?: number;
  genres?: string[];
  runtime?: number;
  rating?: number;
  tmdbRating?: number;
  imdbRating?: number;
  trailerUrl?: string;
  language?: string;
  budget?: string | number;
  revenue?: string | number;
  director?: string;
  actors?: string[];
};